# Generated by Django 3.0 on 2019-12-12 06:32

from django.db import migrations, models
"""
django.db.migrationsというところにあるクラスで、マイグレーションはこのクラスを継承している
"""


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [#実行する処理内容をまとめたもの
        migrations.CreateModel(#モデルを基にでーぶるを作るためのクラス
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=200)),
                ('gender', models.BooleanField()),
                ('age', models.IntegerField(default=0)),
                ('birthday', models.DateField()),
            ],
        ),
    ]
