# Generated by Django 3.0 on 2019-12-14 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handy', '0002_auto_20191214_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='age',
            field=models.IntegerField(default=0, verbose_name='年齢'),
        ),
        migrations.AlterField(
            model_name='form',
            name='birthday',
            field=models.DateField(verbose_name='誕生日'),
        ),
        migrations.AlterField(
            model_name='form',
            name='clab',
            field=models.BooleanField(verbose_name='蟹'),
        ),
        migrations.AlterField(
            model_name='form',
            name='egg',
            field=models.BooleanField(verbose_name='卵'),
        ),
        migrations.AlterField(
            model_name='form',
            name='gender',
            field=models.BooleanField(verbose_name='性別'),
        ),
        migrations.AlterField(
            model_name='form',
            name='mail',
            field=models.EmailField(max_length=200, verbose_name='mail'),
        ),
        migrations.AlterField(
            model_name='form',
            name='milk',
            field=models.BooleanField(verbose_name='牛乳'),
        ),
        migrations.AlterField(
            model_name='form',
            name='name',
            field=models.CharField(max_length=100, verbose_name='名前'),
        ),
        migrations.AlterField(
            model_name='form',
            name='peanuts',
            field=models.BooleanField(verbose_name='落花生'),
        ),
        migrations.AlterField(
            model_name='form',
            name='shrimp',
            field=models.BooleanField(verbose_name='海老'),
        ),
        migrations.AlterField(
            model_name='form',
            name='soba',
            field=models.BooleanField(verbose_name='そば'),
        ),
        migrations.AlterField(
            model_name='form',
            name='wheat',
            field=models.BooleanField(verbose_name='小麦'),
        ),
    ]
